#ifndef GUARD_KUBES_NEW_GAME_CUSTOM_WARP_H
#define GUARD_KUBES_NEW_GAME_CUSTOM_WARP_H

#define KUBES_NEW_GAME_CUSTOM_WARP \
    SetWarpDestination(MAP_GROUP(MAP_CAVE_TOWN_00), MAP_NUM(MAP_CAVE_TOWN_00), WARP_ID_NONE, -1, -1); \
    WarpIntoMap();

#endif // GUARD_KUBES_NEW_GAME_CUSTOM_WARP_H
