//
// Created by kubes on 10/9/26.
//
#ifndef GUARD_KUBES_MACROS_H
#define GUARD_KUBES_MACROS_H

#define DUNGEON_TOWN_COUNT 2
#define NUM_PICKUP_DESCRIPTIONS_PER_DUNGEON 8
#define NUM_OVERWORLD_MONSTER_DESCRIPTIONS_PER_DUNGEON 8

#endif // GUARD_KUBES_MACROS_H
